---
- name: Gather facts about the EC2 instance
  hosts: ec2
  gather_facts: no
  become: true
  vars_files:
    - vars.yaml
  vars:
     ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: Add tags to the EC2 instance
      ec2_tag:
        resource: "{{ resource_id }}"
        region: "us-east-1"
        state: present
        tags:
          Name: wordpress_prod_nv
          Environment: ProductionNew 
